
language: cpp
dist:     xenial
compiler:
  - gcc
  - clang
cache: ccache

# addons:
#   apt:
#     update: true
#     sources:
#       # PPAs for newer toolchains
#       - ubuntu-toolchain-r-test
#     packages:
#       # Extra toolchains
#       - gcc-7
#       - g++-7
#       # Build dependencies
#       - byacc
#       - flex
#       - cmake
#       - make
#       - automake
#       - autoconf
#       - libtool
#       - pkg-config
#   homebrew:
#     packages:
#       - libffi
#       - gettext
#       - glib
#       - pixman

# env:
#   global:
#     - SRC_DIR="."
#     - BUILD_DIR="build"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y byacc flex cmake make automake autoconf libtool pkg-config

before_script:
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake .. || { cat config.log && exit 1; }
script:
  - make -j3 && make test

# matrix:
#   include:
#     - env:
#         - CONFIG=""

#     # MacOSX builds
#     - env:
#         - CONFIG=""
#       os: osx
#       osx_image: xcode9.4
#       compiler: clang
