
language: cpp
dist:     xenial
compiler:
  - gcc
  ## libjit gen-apply segfaults when built with clang
  # - clang
cache: ccache

env:
  global:
    - SRC_DIR="."
    - BUILD_DIR="build"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y byacc flex cmake make automake autoconf libtool pkg-config texinfo

before_script:
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake .. || { cat config.log && exit 1; }
script:
  - make -j3 && make test

matrix:
  include:
    # MacOSX build
    - os: osx
      osx_image: xcode9.4
      compiler:  clang
