
language: cpp
cache: ccache

addons:
  apt:
    packages:
      - cmake
      ## for libjit
      - automake
      - autoconf
      - libtool
      - pkg-config
      - texinfo
      - byacc
      - flex
  homebrew:
    packages:
      ## for libjit
      - texinfo
      - byacc
      - flex

env:
  global:
    - SRC_DIR="."
    - BUILD_DIR="build"

before_script:
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake .. || { cat config.log && exit 1; }
script:
  - make VERBOSE=1 V=1 -j3 && make test

matrix:
  include:
    # Linux build
    - os:       linux
      dist:     xenial
      compiler: gcc
      ## NOTE: libjit gen-apply segfaults when built with Travis's clang

    # MacOSX build
    - os:        osx
      # osx_image: xcode10.1
      compiler:  clang
